openapi: 3.0.3
info:
  title: 臺北市立聯合醫院 單張交換 to FHIR - API 使用說明書
  description: |-
    新光醫院 交換單張 XML to FHIR :

            API 0.1.0 based on the OpenAPI 3.0 specification.

    概述 : 

            將現行資料轉成FHIR 並存入FHIR Server

    對象 :

            1.出院病摘
            2.門診病歷(第二階段)
            3.血液檢驗(第二階段)
            4.檢查報告(第二階段)

    方法 : 
            
            依現行衛生福利部電子病歷FHIR推動專區公告標準，將欄位對應至FHIR相對resourceType欄位，存入FHIR Server

    配套 : 

            上傳後至FHIR Portal，查詢上傳資料狀態

    注意事項 :
    
            1.Request body 內 Example Value 與 Schema 僅為說明格式，section 及 entry 重複格式不逐一說明，詳細說明請參照範例資料註解
            2.測試時請由下方連結下載範例資料複製貼上至 Request body 內 Example Value 執行
            3.後續維護更新責任者-緯謙科技

    範例資料:
    - [出院病摘單測試資料](/DischargeSummary)
    - [門診病例測試資料(預留)]
    - [血液檢驗測試資料(預留)]
    
    服務連結:
    - [TPEH FHIR Portal](http://10.200.251.72:8000/)
    - [TPEH FHIR server](http://10.200.251.72:8080/)
    - [TPEH FHIR API](http://10.200.251.72:8888/)
    - [TPEH API swagger](http://10.200.251.72:8800/)
    
    FHIR標準參照:
    - [衛生福利部電子病歷FHIR推動專區](https://emr.mohw.gov.tw/myemr/fhir.html)
    
    維護專區:
    - [緯謙科技](https://www.wiadvance.com/)    
    - [專案負責部門 : T02300 ]
    - [電話 : 02-66126262]
    - [分機 : 14711 ]

  contact:
    email: Gojim.Yu@wiadvance.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.0
externalDocs:
  description: Find out more about 緯謙科技
  url: https://www.wiadvance.com/
servers:
  - url: http://10.200.251.72:8888
tags:
  - name: 交換單張
    description: 公告交換單張標準
    externalDocs:
      description: 衛生福利部電子病歷FHIR推動專區
      url: https://emr.mohw.gov.tw/myemr/fhir.html
paths:
  /:
    get:
      tags:
        - Server
      summary: 回傳伺服器狀態
      description: 回傳伺服器狀態

      operationId: getInventory
      parameters: []
      responses:
        '200':
          description: "Server Status : run (正常)"
        '500':
          description: "internal server error (內部伺服器錯誤)"
  /DischargeSummary/{DischargeSummary_Id}:
    post:
      tags:
        - 出院病摘單
      summary: 新增出院病摘單資料
      description: 將出院病摘單資料轉為FHIR並儲存至FHIR server
      operationId: add_DischargeSummary
      parameters: 
        - name: DischargeSummary_Id
          in: path
          description: ID of DischargeSummary to add
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Composition_DischargeSummary
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DischargeSummary_ApiJSON'
        required: true
      responses:
        '201':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Composition_DischargeSummary_ApiResponse_JSON'
      security:
         - api_key: []
    get:
      tags:
        - 出院病摘單
      summary: 取得出院病摘單資料(預留)
      description: 取得出院病摘單資料
      operationId: get_DischargeSummary
      parameters: 
        - name: DischargeSummary_Id
          in: path
          description: ID of DischargeSummary to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Composition_DischargeSummary_ApiResponse_JSON'
    put:
      tags:
        - 出院病摘單
      summary: 更新出院病摘單資料(預留)
      description: 更新出院病摘單資料(預留)
      operationId: put_DischargeSummary
      parameters: 
        - name: DischargeSummary_Id
          in: path
          description: ID of DischargeSummary to update
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Composition_DischargeSummary
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Composition_DischargeSummary_ApiResponse_JSON'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Composition_DischargeSummary_ApiResponse_JSON'
      security:
        - wiadvance_auth:
            - put
    delete:
      tags:
        - 出院病摘單
      summary: 刪除出院病摘單資料(預留)
      description: 刪除出院病摘單資料(預留)
      operationId: delete_DischargeSummary
      parameters: 
        - name: DischargeSummary_Id
          in: path
          description: ID of DischargeSummary to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OperationOutcome
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Delete_Reaponse_Json'
      security:
        - wiadvance_auth:
            - delete
        
  /VisitNote/{VisitNote_Id}:
    post:
      tags:
        - 門診病例
      summary: 新增門診病例資料(預留)
      description: 將門診病例轉為FHIR並儲存至FHIR server
      operationId: add_VisitNote
      parameters: 
        - name: VisitNote_Id
          in: path
          description: ID of VisitNote to add
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Composition_VisitNote
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DischargeSummary_ApiJSON'
        required: true
      responses:
        '201':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Composition_VisitNote_ApiResponse_JSON'
      security:
         - api_key: []
    get:
      tags:
        - 門診病例
      summary: 取得門診病例資料(預留)
      description: 取得門診病例資料(預留)
      operationId: get_VisitNote
      parameters: 
        - name: VisitNote_Id
          in: path
          description: ID of VisitNote to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Composition_VisitNote_ApiResponse_JSON'
    put:
      tags:
        - 門診病例
      summary: 更新門診病例資料(預留)
      description: 更新門診病例資料(預留)
      operationId: put_VisitNote
      parameters: 
        - name: VisitNote_Id
          in: path
          description: ID of VisitNote to update
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Composition_VisitNote
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Composition_VisitNote_ApiResponse_JSON'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Composition_VisitNote_ApiResponse_JSON'
      security:
        - wiadvance_auth:
            - put
    delete:
      tags:
        - 門診病例
      summary: 刪除門診病例資料(預留)
      description: 刪除門診病例資料(預留)
      operationId: delete_VisitNote
      parameters: 
        - name: VisitNote_Id
          in: path
          description: ID of VisitNote to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OperationOutcome
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Delete_Reaponse_Json'
      security:
        - wiadvance_auth:
            - delete
            
  /BloodExamination/{BloodExamination_Id}:
    post:
      tags:
        - 血液檢驗
      summary: 新增血液檢驗資料(預留)
      description: 將血液檢驗轉為FHIR並儲存至FHIR server
      operationId: add_BloodExamination
      parameters: 
        - name: BloodExamination_Id
          in: path
          description: ID of BloodExamination to add
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Composition_BloodExamination
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DischargeSummary_ApiJSON'
        required: true
      responses:
        '201':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Composition_VisitNote_ApiResponse_JSON'
      security:
         - api_key: []
    get:
      tags:
        - 血液檢驗
      summary: 取得血液檢驗資料(預留)
      description: 取得血液檢驗資料(預留)
      operationId: get_BloodExamination
      parameters: 
        - name: BloodExamination_Id
          in: path
          description: ID of BloodExamination to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Composition_VisitNote_ApiResponse_JSON'
    put:
      tags:
        - 血液檢驗
      summary: 更新血液檢驗資料(預留)
      description: 更新血液檢驗資料(預留)
      operationId: put_BloodExamination
      parameters: 
        - name: BloodExamination_Id
          in: path
          description: ID of BloodExamination to update
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Composition_BloodExamination
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Composition_VisitNote_ApiResponse_JSON'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Composition_VisitNote_ApiResponse_JSON'
      security:
        - wiadvance_auth:
            - put
    delete:
      tags:
        - 血液檢驗
      summary: 刪除血液檢驗資料(預留)
      description: 刪除血液檢驗資料(預留)
      operationId: delete_BloodExamination
      parameters: 
        - name: BloodExamination_Id
          in: path
          description: ID of BloodExamination to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OperationOutcome
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Delete_Reaponse_Json'
      security:
        - wiadvance_auth:
            - delete
components:
  schemas:
    ContentPackage:
          type: object
          properties:
            cdp:ContentContainer:
              type: object
              properties:
                cdp:StructuredContent:
                  type: object
                  properties:
                    ClinicalDocument:
                      type: object
                      properties:
                        typeId:
                          type: string
                          example: ""
                        templateId:
                          type: string
                          example: ""
                        id:
                          type: string
                          example: ""
                        code:
                          type: string
                          example: ""
                        title:
                            type: string
                            example: "出院病摘單"
                        effectiveTime:
                          type: object
                          properties:
                            value:
                              type: string
                              example: "文件日期"
                              xml:
                                attribute: true
                        confidentialityCode:
                          type: object
                          properties:
                            code:
                              type: string
                              example: "機密性"
                              xml:
                                attribute: true
                        languageCode:
                          type: object
                          properties:
                            code:
                              type: string
                              example: "語言碼"
                              xml:
                                attribute: true
                        recordTarget:
                          type: object
                          properties:
                            patientRole:
                              type: object
                              properties:

                                id:
                                  type: object
                                  properties:
                                    extension:
                                      type: string
                                      example: "病歷號碼"
                                      xml:
                                        attribute: true
                                patient:
                                  type: object
                                  properties:
                                    id:
                                      type: object
                                      properties:
                                        extension:
                                          type: string
                                          example: "身分證號"
                                          xml:
                                            attribute: true
                                    name:
                                      type: string
                                      example: "姓名"
                                    administrativeGenderCode:
                                      type: object
                                      properties:
                                        code:
                                          type: string
                                          example: "性別"
                                          xml:
                                            attribute: true
                                    birthTime:
                                      type: object
                                      properties:
                                        value:
                                          type: string
                                          example: "出生日期"
                                          xml:
                                            attribute: true
                                providerOrganization:
                                      type: object
                                      properties:
                                        id:
                                          type: object
                                          properties:
                                            extension:
                                              type: string
                                              example: "醫事機構代碼"
                                              xml:
                                                attribute: true
                                        name:
                                          type: string
                                          example: "醫事機構名稱"
                        author:
                          type: object
                          properties:
                            time:
                              type: object
                              properties:
                                value:
                                  type: string
                                  example: "醫師紀錄日期時間"
                                  xml:
                                    attribute: true
                            assignedAuthor:
                              type: object
                              properties:
                                id:
                                  type: object
                                  properties:
                                    extension:
                                      type: string
                                      example: "醫師醫院代碼"
                                      xml:
                                        attribute: true
                                assignedPerson:
                                  type: object
                                  properties:
                                    name:
                                      type: string
                                      example: "醫師姓名"
                        custodian:
                          type: object
                          properties:
                            assignedCustodian:
                              type: object
                              properties:
                                representedCustodianOrganization:
                                  type: object
                                  properties:
                                    id:
                                      type: object
                                      properties:
                                        extension:
                                          type: string
                                          example: "醫事機構代碼"
                                          xml:
                                            attribute: true
                                    name:
                                      type: string
                                      example: "醫事機構名稱  "
                        componentOf:
                          type: object
                          properties:
                            encompassingEncounter:
                              type: object
                              properties:
                                effectiveTime:
                                  type: object
                                  properties:
                                    value:
                                      type: string
                                      example: "門診日期"
                                      xml:
                                        attribute: true
                                    location:
                                      type: object
                                      properties:
                                        healthCareFacility:
                                          type: object
                                          properties:
                                            location:
                                              type: object
                                              properties:
                                                name:
                                                  type: string
                                                  example: "科別"
                        component:
                          type: object
                          properties:
                            structuredBody:
                              type: object
                              properties:
                                component:
                                  properties:
                                    section:
                                      properties:
                                        code:
                                          properties:
                                            code:
                                              type: string
                                              example: "LOINC code"
                                              xml:
                                                attribute: true
                                            displayName:
                                              type: string
                                              example: "LOINC display"
                                              xml:
                                                attribute: true
                                            title:
                                              type: string
                                              example: "區段項目(實驗室檢查紀錄、重大傷病...)"
                                            text :
                                              properties:
                                                paragraph:
                                                  type: string
                                                  example: "文字敘述"
                                            entry :
                                              properties:
                                                observation:
                                                  type: object
                                                  properties:
                                                    code:
                                                      type: object
                                                      properties:
                                                        code:
                                                          type: string
                                                          example: "ICD 10編碼"
                                                          xml:
                                                            attribute: true
                                                        displayName:
                                                          type: string
                                                          example: "ICD 10名稱"
                                                          xml:
                                                            attribute: true
                                                    text:
                                                      type: string
                                                      example: "文字敘述"
                                                observationMedia:
                                                  type: object
                                                  properties:
                                                    value:
                                                      type: string
                                                      example: "影像檔案Base64編碼"
          xml:
            prefix: cdp
    DischargeSummary_ApiJSON:
      type: object
      properties:
        Hospital_Id:
          type: string
        Hospital_Name:
          type: string
        ID_NUMBER:
          type: string
        CHART_NO:
          type: string
        NAME:
          type: string
        GENDER:
          type: string
        BIRTH_DATE:
          type: string
        DEPARTMENT:
          type: string
        CREATE_DATE:
          type: string
        CREATE_TIME:
          type: string
        TPMI_ID:
          type: string
        PAT_NO:
          type: string
        PAT_SEQ:
          type: string
        BED_NO:
          type: string
        DATE_OF_HOSPITALIZATION:
          type: string
        DISCHARGE_DATE:
          type: string
        REFERRING_HOSPITAL_ID:
          type: string
        REFERRING_HOSPITAL_NAME:
          type: string
        IMPRESSION_NAME:
          type: string
        IMPRESSION_CONTENTS:
          type: string
        DISCHARGE_DIAGNOSIS_NAME:
          type: string
        DISCHARGE_DIAGNOSIS_CONTENTS:
          type: string
        CANCER_STAGING_NAME:
          type: string
        CANCER_STAGING_CONTENTS:
          type: string
        CHIEF_COMPLAINT_NAME:
          type: string
        CHIEF_COMPLAINT_CONTENTS:
          type: string
        PRESENT_ILLNESS_NAME:
          type: string
        PRESENT_ILLNESS_CONTENTS:
          type: string
        FAMILY_TREE_NAME:
          type: string
        FAMILY_TREE_CONTENTS:
          type: string
        PHYSICAL_EXAMINATION_NAME:
          type: string
        PHYSICAL_EXAMINATION_CONTENTS:
          type: string
        LABORATORY_DATA_NAME:
          type: string
        LABORATORY_DATA_CONTENTS:
          type: string
        SPECIFIC_EXAMINATION_NAME:
          type: string
        SPECIFIC_EXAMINATION_CONTENTS:
          type: string
        IMAGING_STUDY_NAME:
          type: string
        IMAGING_STUDY_CONTENTS:
          type: string
        PATHOLOGY_REPORT_NAME:
          type: string
        PATHOLOGY_REPORT_CONTENTS:
          type: string
        SURGICAL_METHOD_AND_FINDING_NAME:
          type: string
        SURGICAL_METHOD_AND_FINDING_CONTENTS:
          type: string
        HOSPITAL_COURSE_NAME:
          type: string
        HOSPITAL_COURSE_CONTENTS:
          type: string
        COMORBIDITES_NAME:
          type: string
        COMORBIDITES_CONTENTS:
          type: string
        INSTRUCTIONS_ON_DISCHARGE_NAME:
          type: string
        INSTRUCTIONS_ON_DISCHARGE_CONTENTS:
          type: string
        DISCHARGE_STATUS_NAME:
          type: string
        DISCHARGE_STATUS_CONTENTS:
          type: string
        OTHER_NAME:
          type: string
        OTHER_CONTENTS:
          type: string
        Receiving_hospital_id:
          type: string
        Receiving_hospital_name:
          type: string
        PHYSICIAN_NAME:
          type: string
        RESULT_MSG:
          type: string
      example:
        Hospital_Id: 0101090517
        Hospital_Name: 市立聯合醫院仁愛院區
        ID_NUMBER: 1234567890
        CHART_NO: 1234567890
        NAME: 陳156439
        GENDER: M
        BIRTH_DATE: 19591125
        DEPARTMENT: 整合醫學科
        CREATE_DATE: 20190814
        CREATE_TIME: 1406
        TPMI_ID: 20190814
        PAT_NO: 60993600
        PAT_SEQ: G01526
        BED_NO: G91702
        DATE_OF_HOSPITALIZATION: 20190415
        DISCHARGE_DATE: 20190422
        REFERRING_HOSPITAL_ID: 1234567890
        REFERRING_HOSPITAL_NAME: 醫院
        IMPRESSION_NAME: 1.入院診斷(Admission Diagnosis)
        IMPRESSION_CONTENTS: XXXX
        DISCHARGE_DIAGNOSIS_NAME: 2.出院診斷(Discharge Diagnosis)
        DISCHARGE_DIAGNOSIS_CONTENTS: XXXX
        CANCER_STAGING_NAME: XXXX
        CANCER_STAGING_CONTENTS: XXXX
        CHIEF_COMPLAINT_NAME: 3.主訴(Chief Complaint)
        CHIEF_COMPLAINT_CONTENTS: XXXX
        PRESENT_ILLNESS_NAME: 4.病史(Medical History)
        PRESENT_ILLNESS_CONTENTS: XXXX
        FAMILY_TREE_NAME: XXXX
        FAMILY_TREE_CONTENTS: XXXX
        PHYSICAL_EXAMINATION_NAME: 5.體檢發現(Physical Findings)
        PHYSICAL_EXAMINATION_CONTENTS: XXXX        
        LABORATORY_DATA_NAME: 9.一般記錄(Laboratory Reports)
        LABORATORY_DATA_CONTENTS: XXXX
        SPECIFIC_EXAMINATION_NAME: 10.特殊檢查(Specific Examinations)
        SPECIFIC_EXAMINATION_CONTENTS: XXXX
        IMAGING_STUDY_NAME: 11.放射線報告(Radiology Reports)
        IMAGING_STUDY_CONTENTS: XXXX
        PATHOLOGY_REPORT_NAME: 12.病理報告(包括病理發現)(Pathological Reports)
        PATHOLOGY_REPORT_CONTENTS: XXXX
        SURGICAL_METHOD_AND_FINDING_NAME: 6.手術日期及方法(Operation Date and Procedures)
        SURGICAL_METHOD_AND_FINDING_CONTENTS: XXXX
        HOSPITAL_COURSE_NAME: 7.住院治療經過(Treatment Progress)
        HOSPITAL_COURSE_CONTENTS: XXXX
        COMORBIDITES_NAME: 8.合併症(Complications)
        COMORBIDITES_CONTENTS: XXXX
        INSTRUCTIONS_ON_DISCHARGE_NAME: 14.出院指示(Discharge Instructions)
        INSTRUCTIONS_ON_DISCHARGE_CONTENTS: XXXX
        DISCHARGE_STATUS_NAME: 15.出院時情況(Status on Discharge)
        DISCHARGE_STATUS_CONTENTS: XXXX
        OTHER_NAME: 13.其他(Others)
        OTHER_CONTENTS: XXXX
        Receiving_hospital_id: 1234567890
        Receiving_hospital_name: 醫院
        PHYSICIAN_NAME: XXXX
        RESULT_MSG: XXXX
    Composition_VisitNote_ApiResponse_JSON:
      type: object
      properties:
        resourceType:
          type: string
        id:
          type: string
        meta:
          type: object
          properties:
            versionId:
              type: string
            lastUpdated:
              type: string
            source:
              type: string
        language:
          type: string
        text:
          type: object
          properties:
            status:
              type: string
            div:
              type: string
        status:
          type: string
        type:
          type: object
          properties:
            coding:
              type: object
              properties:
                system:
                  type: string
                code:
                  type: string
                display:
                  type: string
        subject:
          type: object
          properties:
            reference:
              type: string
            display:
              type: string
        encounter:
          type: object
          properties:
            reference:
              type: string
        date:
          type: string
        author:
          type: object
          properties:
            reference:
              type: string
            display:
              type: string
        title:
          type: string
        confidentiality:
          type: string
        attester:
          type: object
          properties:
            mode:
              type: string
            time:
              type: string
        custodian:
          type: object
          properties:
            reference:
              type: string
            display:
              type: string
        section:
          type: object
          properties:
            title:
              type: string
            code:
              type: object
              properties:
                coding:
                  type: object
                  properties:
                    system:
                      type: string
                    code:
                      type: string
                    display:
                      type: string
            text:
              type: object
              properties:
                status:
                  type: string
                div:
                  type: string
            entry:
              type: object
              properties:
                reference:
                  type: string
      example:
        resourceType: Composition
        id: '1'
        meta:
          versionId: '1'
          lastUpdated: '2023-03-08T06:42:02.621+00:00'
          source: '#E3Wp8IdPMe08QsvA'
        language: zh-TW
        text:
          status: generated
          div: '<div xmlns=\"http://www.w3.org/1999/xhtml\">\t    \n\t\t\t<table border=\"1\">\n\t\t\t\t<caption>門診病歷</caption>\n\t\t\t\t<tr><th>身分證字號</th><th>病歷號</th><th>病人姓名</th><th>性別</th><th>出生日期</th><th>文件列印日期</th><th>醫師姓名</th><th>醫師紀錄日期時間</th><th>醫院名稱</th><th>科別</th><th>門診日期</th></tr>\n\t\t\t\t<tr><td>Z123456789</td><td>123456</td><td>趙錢孫</td><td>男</td><td>1997-01-01</td><td>2010-09-04</td><td>賴一施 </td><td>2010-09-04</td><td>國立臺灣大學醫學院附設醫院</td><td>家醫科</td><td>2010-08-10</td></tr>\n\t\t\t</table>\n\t\t</div>'
        status: preliminary
        type:
          coding:
            - system: http://loinc.org
              code: 28579-1
              display: Visit note
        subject:
          reference: https://fhirtest.uhn.ca/baseR4/Patient/129257
          display: 趙錢孫
        encounter:
          reference: https://fhirtest.uhn.ca/baseR4/Encounter/129801
        date: 2010-08-01T11:34:00
        author:
          - reference: https://fhirtest.uhn.ca/baseR4/Practitioner/129288
            display: 賴一施
        title: 門診病歷
        confidentiality: N
        attester:
          - mode: professional
            time: 2010-07-31
        custodian:
          reference: https://fhirtest.uhn.ca/baseR4/Organization/129188
          display: 國立臺灣大學醫學院附設醫院
        section:
          - title: 實驗室檢查紀錄
            code:
              coding:
                - system: http://loinc.org
                  code: 19146-0
                  display: Reference lab test results
            text:
              status: generated
              div: '<div xmlns=\"http://www.w3.org/1999/xhtml\">\n\t\t\t\t<br/>\n\t\t\t\t<table>\n\t\t\t\t\t<tr><b>實驗室檢查紀錄:病人血型及D抗原性</b></tr>\n\t\t\t\t\t<tr>血型:B</tr>\n\t\t\t\t\t<tr>D抗原性:Rh+</tr>\n\t\t\t\t</table>\n\t\t\t</div>'
            entry:
                - reference: https://fhirtest.uhn.ca/baseR4/Observation/127858
          - title: 出院診斷
            code:
              coding:
                - system: http://loinc.org
                  code: 11535-2
                  display: Hospital discharge Dx Narrative
            text:
              status: generated
              div: '<div xmlns="http://www.w3.org/1999/xhtml"><br/><table><tr><b>出院診斷:</b></tr><tr>結核病(Tuberculosis)</tr></table></div>'
            entry:
              - reference: https://fhirtest.uhn.ca/baseR4/Condition/128907
    Composition_DischargeSummary_ApiResponse_JSON:
      type: object
      properties:
        resourceType:
          type: string
        id:
          type: string
        meta:
          type: object
          properties:
            versionId:
              type: string
            lastUpdated:
              type: string
            source:
              type: string
        language:
          type: string
        text:
          type: object
          properties:
            status:
              type: string
            div:
              type: string
        status:
          type: string
        type:
          type: object
          properties:
            coding:
              type: object
              properties:
                system:
                  type: string
                code:
                  type: string
                display:
                  type: string
        subject:
          type: object
          properties:
            reference:
              type: string
            display:
              type: string
        encounter:
          type: object
          properties:
            reference:
              type: string
        date:
          type: string
        author:
          type: object
          properties:
            reference:
              type: string
            display:
              type: string
        title:
          type: string
        confidentiality:
          type: string
        attester:
          type: object
          properties:
            mode:
              type: string
            time:
              type: string
        custodian:
          type: object
          properties:
            reference:
              type: string
            display:
              type: string
        section:
          type: object
          properties:
            title:
              type: string
            code:
              type: object
              properties:
                coding:
                  type: object
                  properties:
                    system:
                      type: string
                    code:
                      type: string
                    display:
                      type: string
            text:
              type: object
              properties:
                status:
                  type: string
                div:
                  type: string
            entry:
              type: object
              properties:
                reference:
                  type: string
      example:
        resourceType: Composition
        id: '1'
        meta:
          versionId: '1'
          lastUpdated: '2023-03-08T06:42:02.621+00:00'
          source: '#E3Wp8IdPMe08QsvA'
        language: zh-TW
        text:
          status: generated
          div: >-
            <div xmlns="http://www.w3.org/1999/xhtml"><table
            border="1"><caption>出院病摘單</caption><tr><th>身分證字號</th><th>病歷號</th><th>病人姓名</th><th>性別</th><th>出生日期</th><th>文件列印日期</th><th>醫師姓名</th><th>醫師記錄日期時間</th><th>醫院名稱</th><th>住院日期</th><th>出院日期</th><th>轉出醫事機構名稱</th><th>轉入醫事機構名稱</th></tr><tr><td>Z123456789</td><td>123456</td><td>趙錢孫</td><td>男</td><td>1997-01-01</td><td>2010-08-01</td><td>賴一施
            </td><td>2010-07-31</td><td>國立臺灣大學醫學院附設醫院</td><td>2010-07-01</td><td>2010-07-31</td><td>陽明大學附設醫院護理之家</td><td>國立臺灣大學醫學院附設醫院</td></tr></table></div>
        status: preliminary
        type:
          coding:
            - system: http://loinc.org
              code: 18842-5
              display: Discharge Summary
        subject:
          reference: https://fhirtest.uhn.ca/baseR4/Patient/129257
          display: 趙錢孫
        encounter:
          reference: https://fhirtest.uhn.ca/baseR4/Encounter/129801
        date: '2010-08-01T11:34:00'
        author:
          - reference: https://fhirtest.uhn.ca/baseR4/Practitioner/129288
            display: 賴一施
        title: 出院病摘
        confidentiality: 'N'
        attester:
          - mode: professional
            time: '2010-07-31'
        custodian:
          reference: https://fhirtest.uhn.ca/baseR4/Organization/129188
          display: 國立臺灣大學醫學院附設醫院
        section:
          - title: 住院臆斷
            code:
              coding:
                - system: http://loinc.org
                  code: 46241-6
                  display: Hospital admission diagnosis Narrative - Reported
            text:
              status: generated
              div: <div xmlns="http://www.w3.org/1999/xhtml"><br/><table><tr><b>住院臆斷:</b></tr><tr>有軌電車乘客在交通意外事故中與機動車輛碰撞時受傷之初期照護</tr></table></div>
            entry:
              - reference: https://fhirtest.uhn.ca/baseR4/Condition/128907
    Delete_Reaponse_Json:
      type: object
      properties:
        resourceType:
          type: string
        issue:
          type: object
          properties:
            severity:
              type: string
            code:
              type: string
            diagnostics:
              type: string
            details:
              type: object
              properties:
                coding:
                  type: object
                  properties:
                    system:
                      type: string
                    code:
                      type: string
                    display:
                      type: string

      example:
        resourceType: OperationOutcome
        issue:
          - severity: information
            code: informational
            details: 
              coding:
                - system: https://hapifhir.io/fhir/CodeSystem/hapi-fhir-storage-response-code
                  code: SUCCESSFUL_DELETE
                  display: Delete succeeded.
            diagnostics: Successfully deleted 1 resource(s). Took 16ms.
  securitySchemes:
    wiadvance_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://www.wiadvance.com/oauth/authorize
          scopes:
            put: 更新資料
            delete: 刪除資料
      x-tokenInfoFunc: swagger_server.controllers.authorization_controller.check_petstore_auth
      x-scopeValidateFunc: >-
        swagger_server.controllers.authorization_controller.validate_scope_petstore_auth
    api_key:
      type: apiKey
      name: api_key
      in: header
      x-apikeyInfoFunc: swagger_server.controllers.authorization_controller.check_api_key
